### ISSUE TITLE
Demo cannot Can't instantiate class Syn.Speech.Recognizers.Recognizer

### ISSUE THREAD

**Issue by sven-borden** [SynHub/Syn.Speech.Demo#2]
While trying to test the Demo. It fails at every points giving this error message : 
`
26.02.2017 12:46:46 Info UnitManager UnitManager.newProperties
26.02.2017 12:46:46 Info Sphinx3Loader Loading Sphinx3 acoustic model: mdef
26.02.2017 12:46:46 Info Sphinx3Loader     modelName: mdef
26.02.2017 12:46:46 Info Sphinx3Loader     dataLocation   : 
26.02.2017 12:46:46 Error RecognitionContext Property exception component:'recognizer' property:'' - Can't instantiate class Syn.Speech.Recognizers.Recognizer
Syn.Speech.Util.Props.InternalConfigurationException: Can't instantiate class Syn.Speech.Recognizers.Recognizer ---> Syn.Speech.Util.Props.InternalConfigurationException: Can't instantiate class Syn.Speech.Decoders.Decoder ---> Syn.Speech.Util.Props.InternalConfigurationException: Can't instantiate class Syn.Speech.Decoders.Search.SimpleBreadthFirstSearchManager ---> Syn.Speech.Util.Props.InternalConfigurationException: Can't instantiate class Syn.Speech.Decoders.Scorer.SimpleAcousticScorer ---> Syn.Speech.Util.Props.InternalConfigurationException: Can't instantiate class Syn.Speech.FrontEnds.FrontEnd ---> Syn.Speech.Util.Props.InternalConfigurationException: Can't instantiate class Syn.Speech.FrontEnds.AutoCepstrum ---> Syn.Speech.Util.Props.PropertyException: Could not find a part of the path 'C:\Users\Sven Borden\Downloads\syn-speech-demo-master\syn-speech-demo-master\SpeechDemo\bin\Debug\Models\means'. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Sven Borden\Downloads\syn-speech-demo-master\syn-speech-demo-master\SpeechDemo\bin\Debug\Models\means'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at Syn.Speech.Linguist.Acoustic.Tiedstate.Sphinx3Loader.ReadS3BinaryHeader(String path, Dictionary`2 _props)
   at Syn.Speech.Linguist.Acoustic.Tiedstate.Sphinx3Loader.LoadDensityFile(String path, Single floor)
   at Syn.Speech.Linguist.Acoustic.Tiedstate.Sphinx3Loader.LoadModelFiles(String modelDef)
   at Syn.Speech.Linguist.Acoustic.Tiedstate.Sphinx3Loader.Load()
   at Syn.Speech.FrontEnds.AutoCepstrum.NewProperties(PropertySheet ps)
   --- End of inner exception stack trace ---
   at Syn.Speech.FrontEnds.AutoCepstrum.NewProperties(PropertySheet ps)
   at Syn.Speech.Util.Props.ConfigurableAdapter.Syn.Speech.Util.Props.IConfigurable.NewProperties(PropertySheet ps)
   at Syn.Speech.Util.Props.PropertySheet.GetOwner()
   --- End of inner exception stack trace ---
   at Syn.Speech.Util.Props.PropertySheet.GetOwner()
   at Syn.Speech.Util.Props.ConfigurationManager.Lookup(String instanceName)
   at Syn.Speech.Util.Props.PropertySheet.GetComponentList[T](String name)
   at Syn.Speech.FrontEnds.FrontEnd.NewProperties(PropertySheet ps)
   at Syn.Speech.Util.Props.ConfigurableAdapter.Syn.Speech.Util.Props.IConfigurable.NewProperties(PropertySheet ps)
   at Syn.Speech.Util.Props.PropertySheet.GetOwner()
   --- End of inner exception stack trace ---
   at Syn.Speech.Util.Props.PropertySheet.GetOwner()
   at Syn.Speech.Util.Props.PropertySheet.GetComponent(String name)
   at Syn.Speech.Decoders.Scorer.SimpleAcousticScorer.NewProperties(PropertySheet ps)
   at Syn.Speech.Util.Props.PropertySheet.GetOwner()
   --- End of inner exception stack trace ---
   at Syn.Speech.Util.Props.PropertySheet.GetOwner()
   at Syn.Speech.Util.Props.PropertySheet.GetComponent(String name)
   at Syn.Speech.Decoders.Search.SimpleBreadthFirstSearchManager.NewProperties(PropertySheet ps)
   at Syn.Speech.Util.Props.PropertySheet.GetOwner()
   --- End of inner exception stack trace ---
   at Syn.Speech.Util.Props.PropertySheet.GetOwner()
   at Syn.Speech.Util.Props.PropertySheet.GetComponent(String name)
   at Syn.Speech.Decoders.AbstractDecoder.NewProperties(PropertySheet ps)
   at Syn.Speech.Decoders.Decoder.NewProperties(PropertySheet ps)
   at Syn.Speech.Util.Props.PropertySheet.GetOwner()
   --- End of inner exception stack trace ---
   at Syn.Speech.Util.Props.PropertySheet.GetOwner()
   at Syn.Speech.Util.Props.PropertySheet.GetComponent(String name)
   at Syn.Speech.Recognizers.Recognizer.NewProperties(PropertySheet propertySheet)
   at Syn.Speech.Util.Props.PropertySheet.GetOwner()
   --- End of inner exception stack trace ---
   at Syn.Speech.Util.Props.PropertySheet.GetOwner()
   at Syn.Speech.Util.Props.ConfigurationManager.Lookup(String instanceName)
   at Syn.Speech.Api.Context..ctor(URL path, Configuration config)
   at Syn.Speech.Api.Context..ctor(Configuration config)
   at Syn.Speech.Api.StreamSpeechRecognizer..ctor(Configuration configuration)
   at SpeechDemo.ViewModel.RecognitionContext.LoadGrammar() in C:\Users\Sven Borden\Downloads\syn-speech-demo-master\syn-speech-demo-master\SpeechDemo\ViewModel\RecognitionContext.cs:line 214`

**Comment by SynHub** [comment]
Please compile you project in "Release" Mode.  The application is not able to find the language models as it is looking it under the "Debug"  folder.
